### PR TITLE
Update gh-collaboration.qmd

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Assignees:

- [x] Making a branch - Tomas, review: Martin
- [x] Making changes - Cormac, review: Guilherme
- [x] Making a draft pull request - Per, review: Verena 
- [x] Making a ready for review pull request - Miguel, review: Tomas
- [x] Code review - Martin, review: Cormac
- [x] Merging - Verena, review: Miguel

### CODE REVIEW

**Comment by mahesh-panchal** [comment]
I definitely messed up in instruction here. 
I was supposed to review the additions before they get merged back into this branch.

**Comment by RedondoMA** [comment]
Sorry, Mahesh! I got it now. I thought you would review it only before merging to the main branch! Good that we had this first introductory lesson :)

**Comment by mahesh-panchal** [comment]
It's good to do this so we know what's working and what's not. 
I also forgot to include how to go over responding to review comment suggestions. 
I can see if branch rules can help, but it seems a review lesson would be a good thing to do soon.

**Comment by mahesh-panchal** [comment]
Perhaps following weeks should be the review lesson, so we do one lesson, review lesson, another lesson, review lesson

**Pull request merged**
