### PR TITLE
Quarto intro cli

### PR DESCRIPTION
**Pull request by MartinPippel**

### CODE REVIEW

**Review by percyfal — CHANGES_REQUESTED** [review]
LGTM - make sure to point the PR to NBISweden:quarto-intro and not NBISweden:main though.

**Review by n-equals-one — APPROVED** [review]
This looks lioke a good summary to me.

**Comment by percyfal** [comment]
@MartinPippel could you change the target branch to NBISweden:quarto-intro?

**Comment by MartinPippel** [comment]
Sorry Per 🫣

**Review by percyfal — APPROVED** [review]

**Pull request merged**
